pipeline {
  agent any
  stages {
    stage('Test') {
      steps {
        sh 'mvn clean install'
      }
   
      post {
        always {
         
          cucumber '**/*.json'
        }
        success {
            echo 'This will run only if successful'
            slackSend channel: 'apitest', color: '#439FE0", message: "Build Started: ${env.JOB_NAME} ${env.BUILD_NUMBER}', message: 'started ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)', tokenCredentialId: 'jenkins-slack-notifier'
        }
        failure {
            echo 'This will run only if failed'
        }
        unstable {
            echo 'This will run only if the run was marked as unstable'
        }
        changed {
            echo 'This will run only if the state of the Pipeline has changed'
            echo 'For example, if the Pipeline was previously failing but is now successful'
        }

      }
    }
  }
}